server:
  port: 8087
spring:
  application:
    name: consume-service

  rabbitmq:
    #127.0.0.1
    host: 127.0.0.1
    port: 5672
    virtual-host: /attendparty
    username: sin_atendary
    password: sin_2020
    listener:
      simple:
        retry:
          max-attempts: 5 #最大重试次数
          max-interval: 20000ms
          initial-interval: 3000ms #重试间隔时间（单位毫秒）
          multiplier: 2
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
