server:
  port: 8888

spring:
  thymeleaf:
    cache: false

  rabbitmq:
    #127.0.0.1
    host: 47.111.182.198
    port: 5672
    virtual-host: /djtravel2
    username: mqtt_test
    password: mqtt_test

  mqtt:
    username: mqtt_test
    #MQTT-密码password: password
    password: mqtt_test
    #MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:1883，tcp://192.168.2.133:1883
    url: tcp://47.111.182.198:1883
    #MQTT-连接服务器默认客户端ID
    client:
      id: sjn
    #MQTT-默认的消息推送主题，实际可在调用接口时指定
    default:
      #订阅主题，多个用‘,’隔开，如：topic,topic1
      topic: topic,topic1
    #连接超时
    completionTimeout: 3000