server:
  port: 8082

spring:
  thymeleaf:
    cache: false

  rabbitmq:
    #127.0.0.1
    host: 127.0.0.1
    port: 5672
    virtual-host: /attendparty
    username: sin_atendary
    password: sin_2020

    mqtt:
      url: tcp://localhost:1883
      username: sin_atendary
      password: sin_2020
      defaultTopic: sin_notice

